### ISSUE TITLE
Asciidoctor generated by Lutaml in ISO 10303-42 is corrupt

### ISSUE THREAD

**Issue by opoudjis** [metanorma/stepmod2mn#93] opened 2023-10-31 09:01 UTC
Follow-on from https://github.com/metanorma/annotated-express/issues/137

The Asciidoctor being generated by stepmod2mn is doing bad nesting of clauses; as a result the bibliography is being gobbled up by the main clause, and ISO is ignoring it as an illegitimate clause.

I will note that because lutaml does not output the asciidoctor it generates to disk, it is impossible to debug its output. This is an oversight, @ronaldtse, and it needs to be fixed. Not by me. But lutaml has been implemented as a black box, and that is impacting any troubleshooting we attempt of it.

For this document, I am attaching a zip of its structure, from clause 4 on. You can see that three clause endings are being missed, and as a result the annexes and bibliography are being improperly nested within a single monster-clause, which Metanorma is having trouble making sense of.

Bad things start happening at geometry_schema.dupin_cyclide_surface, and I note that its document.xml is mangled, with Asciidoctor directives left unprocessed; that tells me that there is a failure to terminate a delimiter in the source Asciidoctor:

````
<clause id="geometry_schema.dupin_cyclide_surface" type="express" inline-header="false" obligation="normative">
<title>dupin_cyclide_surface <xref target="expg.geometry_schema"></xref> <index><primary>dupin_cyclide_surface</primary><secondary>Object definition</secondary></index></title>
<p id="_2b888aec-f6af-4dfb-de7f-7e7d374666c4">A <strong>dupin_cyclide_surface</strong> is a type of <xref target="geometry_schema.elementary_surface">elementary_surface</xref>, that is a generalisation of a <xref target="geometry_schema.toroidal_surface">toroidal_surface</xref> in which the radius of the generatrix varies as it is swept around the directrix, passing through a maximum and a minimum value. The directrix is in general an ellipse, though that fact is not germane to the definition given here. The surface has two orthogonal planes of symmetry, and in both of them its cross-section is a pair of circles.</p>

<p id="_90f1f24d-c6c2-eb01-dbbf-3be3626aac0a">As with the <xref target="geometry_schema.toroidal_surface">toroidal_surface</xref>, self-intersecting forms occur. The Dupin cyclides are special cases of a more general class of surfaces known as <em>generalized cyclides</em> (or sometimes simply <em>cyclides</em>). The present specification does not cover the wider class.</p>

<p id="_bd1fb8e8-c86c-2994-8f75-3a62a82f0a5a">The interpretation of the data is as follows:</p>

<p id="_97c0f82e-28ec-1847-a60c-8e4f7a489008">**[stem]</p>

C = position.location
<formula id="_030576b5-7f3d-3dcc-f613-6998ab27f038"><stem type="MathML" block="true">

...


<asciimath>y = position.p[2]
++++**
[stem]</asciimath></stem></formula>

<p id="_8c74c490-9546-c0c1-2d8b-748f98beecc6">z = position.p[3] (axis of “toroidal_surface”)</p>

[stem]
<p id="_cfe6a2f0-382d-bf9e-25c8-168408e85369">R = “generalised_major_radius”</p>

[stem]
<p id="_a557200a-3e22-7bf8-0e6c-385601c8c37a">r = “generalised_minor_radius”</p>

[stem]
<p id="_4c5af2b9-b62f-fd59-b6e4-2961181b588b">s = skewness</p>

and the surface is parametrised as

image::/Users/nickn/Documents/Arbeit/upwork/ribose/tmp/iso-10303-stepmod/data/resources/geometry_schema/Dupc1.gif[]

where the domain of parametrisation is _0° ≤ u,v ≤ 360°_ , and √ denotes the positive square root. _u_ and _v_ are angular parameters and when numerical values are specified they shall use the current units for <express:measure-schema.plane-angle-measure/>,plane_angle_measure&gt;&gt;.

In the placement coordinate system defined above the Dupin cyclide surface has the algebraic representation _S = 0_, where

````

This seems to have resulted from an attempt to wrap a stem expression in boldface, 

````
**[stem]
++++
....
++++**
````

As you will not be surprised to find, this has ended in tears: directives like `[stem]` are block markup, and cannot be modified by inline markup.

**Comment by opoudjis** [comment] 2023-10-31 09:02
[document.xml.zip](https://github.com/metanorma/stepmod2mn/files/13214259/document.xml.zip)
[a.xml.zip](https://github.com/metanorma/stepmod2mn/files/13214261/a.xml.zip)

**Comment by Intelligent2013** [comment] 2023-10-31 17:46
I think the issue in the `data\resources\geometry_schema\geometry_schema_annotated.exp` (generated by stepmod-utils):
```
[stem]
++++
y = position.p[2]
++++**
[stem]
++++
z = position.p[3] (normal to plane)
++++

and the surface is parametrised as
```

The original `description.xml` is:
```xml
		<p> The data is to be interpreted as follows: </p>
		<b>
			<eqn> C = position.location  </eqn>
			<eqn>  x = position.p[1]     </eqn>
			<eqn> y =  position.p[2]     </eqn>
		</b>
		<eqn>
			<b> z = position.p[3] </b>  (normal to plane)     </eqn>
```

**Comment by ronaldtse** [comment] 2023-10-31 23:24
Thanks @Intelligent2013 , can you please file the issue at stepmod-utils for @HassanAkbar ? Thanks.

**Comment by HassanAkbar** [comment] 2023-11-01 08:51
@ronaldtse @opoudjis I am working on it. As mentioned by @opoudjis that adding `**` will not be modified by `inline markup` so I think we should just remove `**` from around the `[stem]` block & that will fix the problem. Let me know if you are thinking otherwise.

**Comment by opoudjis** [comment] 2023-11-03 04:25
OK, will test in https://github.com/metanorma/annotated-express/issues/137 . If that test is successful, that closes this issue.

**Comment by opoudjis** [comment] 2023-11-05 09:51
How do I test this? I have just recompiled stepmod2mn to 1.22, and the output is unchanged. 

iso-10303-stepmod branch is also SMRLv9, and data/resources/geometry_schema/geometry_schema_annotated.exp is unchanged, it still has the `**[stem]` problem today: https://github.com/metanorma/iso-10303-stepmod/blob/SMRLv9/data/resources/geometry_schema/geometry_schema_annotated.exp#L5657

If iso-10303-stepmod does not change to fix this issue, I cannot test it. @HassanAkbar @Intelligent2013

**Comment by Intelligent2013** [comment] 2023-11-05 14:57
@opoudjis `stepmod2mn` doesn't run the `stepmod-utils`. `stepmod-utils` should be run before `stepmod2mn`. But I don't know who/when/where (which repository/branch) should run `stepmod-utils` to re-generate the .exp files.

**Comment by opoudjis** [comment] 2023-11-05 15:05
stepmod-utils has just been released (can't tell by who), so will see if it's generated new repo contents tomorrow.

**Comment by HassanAkbar** [comment] 2023-11-05 15:28
@Intelligent2013 I’ve updated the `stepmod-utils` to fix this issue and released a new version `0.3.32`, can you incorporate it into `stepmod2mn`.

**Comment by Intelligent2013** [comment] 2023-11-05 15:57
> @Intelligent2013 ... can you incorporate it into `stepmod2mn` ?

@HassanAkbar hmm, it's something new for me. `stepmod2mn` is Java program, `stepmod-utils` is Ruby program. I thought that `stepmod-utils` should run `stepmod2mn` regarding https://github.com/metanorma/stepmod-utils/issues/160

**Comment by HassanAkbar** [comment] 2023-11-05 16:11
@Intelligent2013 I'm a little confused as to what the workflow is. As mentioned by @opoudjis in the issue description

> The Asciidoctor being generated by stepmod2mn is doing bad nesting of clauses; as a result the bibliography is being gobbled up by the main clause, and ISO is ignoring it as an illegitimate clause.

And then you mentioned that it is caused by `stepmod-utils`. Based on that  I assumed that somehow `stepmod2mn` is calling `stepmod-utils`. 

@ronaldtse @opoudjis Can you let me know what the workflow is that is producing the error? So I can try to check what needs to be done to fix the output.

**Comment by ronaldtse** [comment] 2023-11-06 03:45
The workflow here is that we have an annotation workflow that first runs stepmod-utils to annotate EXPRESS files and etc, then we run stepmod2mn to convert the documents.

We now have a single command method in stepmod-utils to run the full flow together.

**Comment by opoudjis** [comment] 2023-11-06 06:52
Now cannot compile Part 42 for a different reason:

````
Image specified at `/Users/nickn/Documents/Arbeit/upwork/ribose/tmp/iso-10303-stepmod/data/resources/geometry_schema/Dupc1.gif` does not exist.
Image specified at `/Users/nickn/Documents/Arbeit/upwork/ribose/tmp/iso-10303-stepmod/data/resources/geometry_schema/RationalLRsurf.gif` does not exist.
````

@HassanAkbar @Intelligent2013 @TRThurman Those gifs are indeed nowhere to be seen in https://github.com/metanorma/iso-10303-stepmod/tree/SMRLv9/data/resources/geometry_schema or https://github.com/metanorma/iso-10303-stepmod-wg12/tree/SMRLv9/data/resources/geometry_schema .

I continue to have no idea who among you fixes that, but that needs to be fixed.

**Comment by opoudjis** [comment] 2023-11-06 06:54
If it helps, the same directory does have RationalLRcurve.gif and RationalLRvol.gif

**Comment by HassanAkbar** [comment] 2023-11-06 07:41
@opoudjis I ran `./exe/stepmod-srl-migrate --stepmod-data-dir "../iso-10303-stepmod-wg12" -s "../stepmod2mn/target/stepmod2mn-1.17.jar"` and both the files that you mentioned were generated, attaching images for reference.

Can you let me know what commands are you running that are causing the error?

<img width="1407" alt="Screenshot 2023-11-06 at 12 13 24 PM" src="https://github.com/metanorma/stepmod2mn/assets/5301572/51898ea3-9fd0-45ee-9202-1b4c82768da2">
<img width="1407" alt="Screenshot 2023-11-06 at 12 14 28 PM" src="https://github.com/metanorma/stepmod2mn/assets/5301572/ff3383c2-1655-4dea-abd3-d087edf9f4a2">

**Comment by HassanAkbar** [comment] 2023-11-06 11:58
@opoudjis I've updated the `stepmod-utils` and released version `0.3.34` and also ran the workflow to update `iso-10303-stepmod` and now the following missing files are present in the folder
- https://github.com/metanorma/iso-10303-stepmod/blob/SMRLv9/data/resources/geometry_schema/Dupc1.gif
- https://github.com/metanorma/iso-10303-stepmod/blob/SMRLv9/data/resources/geometry_schema/RationalLRsurf.gif

**Comment by TRThurman** [comment] 2023-11-06 17:44
@HassanAkbar What is magic about those two files?

**Comment by HassanAkbar** [comment] 2023-11-07 06:48
@TRThurman The files in the `resource_docs folder` are named `DupC1.gif` and `RationalLRSurf.gif` (notice the `C` and `S` are in uppercase) and in the express files they are referenced as `Dupc1.gif` and `RationalLRsurf.gif` respectively. 

As it turns out that in Mac file name comparison is case insensitive so this is working fine for me locally but in GitHub Actions, `Ubuntu` was used and in Ubuntu file name comparison are case sensitive so the files that we need to copy over to the `resources` folder were not found and no copy operation was performed.

**Comment by ronaldtse** [comment] 2023-11-07 08:25
@HassanAkbar and despite now being able to copy the files over, the compilation on Ubuntu will still fail because the referenced file names is still different from the actual file names.

**Comment by HassanAkbar** [comment] 2023-11-07 09:44
@ronaldtse I've updated `stepmod-utils` to name the copied image according to the image used in document, so compilation should work.
The `destination_path` in this [line](https://github.com/metanorma/stepmod-utils/blob/main/exe/stepmod-annotate-all#L95) uses the filename referenced in the document.

**Comment by ronaldtse** [comment] 2023-11-07 10:00
Thanks @HassanAkbar , do we know if there are other files with this problem? Can we fix them once and for all in stepmod-utils?

**Comment by HassanAkbar** [comment] 2023-11-07 10:22
@ronaldtse The current logic that is implemented in `stepmod-utils` will compare the file names without case sensitivity and create output based on the names that are used as reference in the document, so after the latest run for generating `iso-10303-stepmod` all the files like this will be fixed.

**Comment by TRThurman** [comment] 2023-11-07 13:08
> Case-sensitivity is actually an important issue for cross-platform collaboration. The file names must be correct in reference.
> 
> @TRThurman can we get this fixed by WG12?

Yes, we need to log a Jira issue. I will fix it in the wg12-stepdev source for SMRLv11.

**Comment by opoudjis** [comment] 2023-11-08 13:54
The document now compiles, so I'm closing this.

**Comment by opoudjis** [comment] 2023-11-09 08:05
Hassan, sorry, but related issue is still corrupting the Asciidoctor: Stem expressions also must not be italicised:

````
<p id="_9fdbcf0a-5782-b08b-cdfc-812aac623f77">_[stem]</p>
  
|((((S^{c})[F]){ L_{l}^{e}}){E\}){V\}| + |(((S^{c})[F]){ L_{l}^{v}}){V}| — |(((S^{c})[F]){L_{l}}){E}|
++++_
[stem]
````

As it turns out, there is a mechanism to boldface or italicise the contents of a stem expression in Asciimath, which is by inserting font directives:

````
bb ( |((((S^{c})[F]){ L_{l}^{e}}){E\}){V\}| + |(((S^{c})[F]){ L_{l}^{v}}){V}| — |(((S^{c})[F]){L_{l}}){E}| )
````

Boldface in Asciimath is `bb( ... )`, italics is `ii( ... )`

**Comment by HassanAkbar** [comment] 2023-11-10 06:14
Just for confirmation I need to change 
```
_[stem]
++++
|((((S^{c})[F]){ L_{l}^{e}}){E\}){V\}| + |(((S^{c})[F]){ L_{l}^{v}}){V}| - |(((S^{c})[F]){L_{l}}){E}|
++++_
```

to 

```
[stem]
++++
ii( |((((S^{c})[F]){ L_{l}^{e}}){E\}){V\}| + |(((S^{c})[F]){ L_{l}^{v}}){V}| - |(((S^{c})[F]){L_{l}}){E}| )
++++
```

and the same goes for `bold` as well. 
@opoudjis Is this correct?

**Comment by HassanAkbar** [comment] 2023-11-10 06:27
@opoudjis also I could not find `ii` on the [asciimath.org](http://asciimath.org) documentation. Should I add this to `stepmod-utils`?

**Comment by ronaldtse** [comment] 2023-11-10 06:39
@HassanAkbar the AsciiMath language supported by Plurimath is slightly different from asciimath.org. Please confirm with @suleman-uzair -- and we need to document this on plurimath.org

**Comment by opoudjis** [comment] 2023-11-10 09:29
The list of what Suleman has implemented is in

https://github.com/plurimath/plurimath/blob/main/lib/plurimath/utility.rb

These are common in implementations of Asciimath, such as Asciidoctor's, even if they're not mentioned in asciimath.org.

**Comment by ronaldtse** [comment] 2023-11-10 09:39
asciimath.org is run by `AsciiMath.js`, which is a different implementation of AsciiMath than Asciidoctor's `asciimath` gem.

**Comment by opoudjis** [comment] 2023-11-10 10:33
From https://github.com/metanorma/annotated-express/issues/137#issuecomment-1805474802

However, this seems to be ISO-10303-42, clause 4.4.26, formula (9).

I am seeing no boldface in the HTML, which is consistent with them not hitherto being included in the Asciidoc generation. Sure enough, the source Asciidoc in data/resources/geometry_schema/geometry_schema_annotated.exp is:

````
[stem]
++++
λ(u) = C +R(cos(u)x + sin(u)y)
++++
````

The corresponding Express appears to be:

https://github.com/metanorma/iso-10303-stepmod-wg12/blob/85ac47124a35fb985b99d0148e9bbe16609cb197/data/resources/geometry_schema/descriptions.xml#L1407

````
<eqn>  <b> &#955;</b><i>(u)</i> = <b>C</b> +R(cos(<i>u</i>)<b>x</b> + sin(<i>u</i>)<b>y</b>)  </eqn>
````

So @HassanAkbar in the foregoing, the Asciidoctor you need to be generating is:

````
[stem]
++++
bb(λ)ii((u)) = bb(C) +R(cosii((u))bb(x) + sin(ii(u))b(y))
++++
````

The issues we are getting at the moment are far more basic: entire equations are being mangled because bold or italics are wrapping the entire equation, resulting in illegal Asciidoctor. But yes, the boldface and italics within equations is also being skipped.

**Closed** 2023-11-12 08:05 UTC
Labels: bug
